/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * matriz.java
 *
 * Created on 16/03/2011, 07:29:13 PM
 */

/**
 *
 * @author Administrador
 */
public class matriz extends javax.swing.JFrame {

    /** Creates new form matriz */
    public matriz() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caja1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        caja2 = new javax.swing.JTextField();
        caja3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        caja4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(caja1);
        caja1.setBounds(30, 20, 210, 30);

        jButton1.setText("Almacenar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 60, 150, 30);
        getContentPane().add(caja2);
        caja2.setBounds(70, 120, 40, 30);
        getContentPane().add(caja3);
        caja3.setBounds(70, 170, 40, 30);

        jLabel1.setText("Fila");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 130, 30, 14);

        jLabel2.setText("Columna");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 180, 50, 14);

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(120, 140, 90, 30);
        getContentPane().add(caja4);
        caja4.setBounds(220, 140, 40, 30);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-293)/2, (screenSize.height-259)/2, 293, 259);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String a=caja1.getText(), opcion;
        char m[][]=new char[3][3];
        char coma, dato;
        char vd [];
        int  columnas=m.length, filas=m[0].length, op, e=0;

        op=a.length();
        for(int i=0;i<op;i++)
        {
            coma=a.charAt(i);
            if(coma==',')
            {
                e=i;
            }
        }
        opcion=a.substring(e+1);
        if("1".equals(opcion))
        {
            for(int i=0;i<m.length; i++)
            {
                for(int j=0;j<m[i].length;j++)
                {
                }
            }
        }
        for(int i=op;i>m.length; i--)
        {
            for(int j=0;j<m[i].length;j++)
            {
                m[i][j]=a.charAt(i);
            }
        }
        caja4.setText(String.valueOf(opcion));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new matriz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField caja1;
    private javax.swing.JTextField caja2;
    private javax.swing.JTextField caja3;
    private javax.swing.JTextField caja4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
